pub enum ErrorTypeEnum {
    ApcIndexMismatch,
    DeviceQueueNotBusy,
    InvalidAffinitySet,
    InvalidDataAccessTrap,
    InvalidProcessAttachAttempt,
    InvalidProcessDetachAttempt,
    InvalidSoftwareInterrupt,
    IrqlNotDispatchLevel,
    IrqlNotGreaterOrEqual,
    IrqlNotLessOrEqual,
    NoExceptionHandlingSupport,
    MaximumWaitObjectsExceeded,
    MutexLevelNumberViolation,
    NoUserModeContext,
    SpinLockAlreadyOwned,
    SpinLockNotOwned,
    ThreadNotMutexOwner,
    TrapCauseUnknown,
    EmptyThreadReaperList,
    CreateDeleteLockNotLocked,
    LastChanceCalledFromKmode,
    CidHandleCreation,
    CidHandleDeletion,
    ReferenceByPointer,
    BadPoolHeader,
    MemoryManagement,
    PfnShareCount,
    PfnReferenceCount,
    NoSpinLockAvailable,
    KmodeExceptionNotHandled,
    SharedResourceConvError,
    KernelApcPendingDuringExit,
    QuotaUnderflow,
    FileSystem,
    FatFileSystem,
    NtfsFileSystem,
    NpfsFileSystem,
    CdfsFileSystem,
    RdrFileSystem,
    CorruptAccessToken,
    SecuritySystem,
    InconsistentIrp,
    PanicStackSwitch,
    PortDriverInternal,
    ScsiDiskDriverInternal,
    DataBusError,
    InstructionBusError,
    SetOfInvalidContext,
    Phase0InitializationFailed,
    Phase1InitializationFailed,
    UnexpectedInitializationCall,
    CacheManager,
    NoMoreIrpStackLocations,
    DeviceReferenceCountNotZero,
    FloppyInternalError,
    SerialDriverInternal,
    SystemExitOwnedMutex,
    SystemUnwindPreviousUser,
    SystemServiceException,
    InterruptUnwindAttempted,
    InterruptExceptionNotHandled,
    MultiprocessorConfigurationNotSupported,
    NoMoreSystemPtes,
    TargetMdlTooSmall,
    MustSucceedPoolEmpty,
    AtdiskDriverInternal,
    NoSuchPartition,
    MultipleIrpCompleteRequests,
    InsufficientSystemMapRegs,
    DerefUnknownLogonSession,
    RefUnknownLogonSession,
    CancelStateInCompletedIrp,
    PageFaultWithInterruptsOff,
    IrqlGtZeroAtSystemService,
    StreamsInternalError,
    FatalUnhandledHardError,
    NoPagesAvailable,
    PfnListCorrupt,
    NdisInternalError,
    PageFaultInNonpagedArea,
    RegistryError,
    MailslotFileSystem,
    NoBootDevice,
    LmServerInternalError,
    DataCoherencyException,
    InstructionCoherencyException,
    XnsInternalError,
    FtdiskInternalError,
    PinballFileSystem,
    CriticalServiceFailed,
    SetEnvVarFailed,
    HalInitializationFailed,
    UnsupportedProcessor,
    ObjectInitializationFailed,
    SecurityInitializationFailed,
    ProcessInitializationFailed,
    Hal1InitializationFailed,
    Object1InitializationFailed,
    Security1InitializationFailed,
    SymbolicInitializationFailed,
    Memory1InitializationFailed,
    CacheInitializationFailed,
    ConfigInitializationFailed,
    FileInitializationFailed,
    Io1InitializationFailed,
    LpcInitializationFailed,
    Process1InitializationFailed,
    RefmonInitializationFailed,
    Session1InitializationFailed,
    Session2InitializationFailed,
    Session3InitializationFailed,
    Session4InitializationFailed,
    Session5InitializationFailed,
    AssignDriveLettersFailed,
    ConfigListFailed,
    BadSystemConfigInfo,
    CannotWriteConfiguration,
    ProcessHasLockedPages,
    KernelStackInpageError,
    Phase0Exception,
    MismatchedHal,
    KernelDataInpageError,
    InaccessibleBootDevice,
    BugcodeNdisDriver,
    InstallMoreMemory,
    SystemThreadExceptionNotHandled,
    UnexpectedKernelModeTrap,
    NmiHardwareFailure,
    SpinLockInitFailure,
    DfsFileSystem,
    SetupFailure,
    MbrChecksumMismatch,
    KernelModeExceptionNotHandled,
    Pp0InitializationFailed,
    Pp1InitializationFailed,
    UpDriverOnMpSystem,
    InvalidKernelHandle,
    KernelStackLockedAtExit,
    InvalidWorkQueueItem,
    BoundImageUnsupported,
    EndOfNtEvaluationPeriod,
    InvalidRegionOrSegment,
    SystemLicenseViolation,
    UdfsFileSystem,
    MachineCheckException,
    UserModeHealthMonitor,
    DriverPowerStateFailure,
    InternalPowerError,
    PciBusDriverInternal,
    MemoryImageCorrupt,
    AcpiDriverInternal,
    CnssFileSystemFilter,
    AcpiBiosError,
    BadExhandle,
    HalMemoryAllocation,
    VideoDriverDebugReportRequest,
    BgiDetectedViolation,
    VideoDriverInitFailure,
    AttemptedSwitchFromDpc,
    ChipsetDetectedError,
    SessionHasValidViewsOnExit,
    NetworkBootInitializationFailed,
    NetworkBootDuplicateAddress,
    InvalidHibernatedState,
    AttemptedWriteToReadonlyMemory,
    MutexAlreadyOwned,
    SpecialPoolDetectedMemoryCorruption,
    BadPoolCaller,
    DriverVerifierDetectedViolation,
    DriverCorruptedExpool,
    DriverCaughtModifyingFreedPool,
    TimerOrDpcInvalid,
    IrqlUnexpectedValue,
    DriverVerifierIomanagerViolation,
    PnpDetectedFatalError,
    DriverLeftLockedPagesInProcess,
    PageFaultInFreedSpecialPool,
    PageFaultBeyondEndOfAllocation,
    DriverUnloadedWithoutCancellingPendingOperations,
    TerminalServerDriverMadeIncorrectMemoryReference,
    DriverCorruptedMmpool,
    DriverIrqlNotLessOrEqual,
    BugcodeIdDriver,
    DriverPortionMustBeNonpaged,
    SystemScanAtRaisedIrqlCaughtImproperDriverUnload,
    DriverPageFaultInFreedSpecialPool,
    DriverPageFaultBeyondEndOfAllocation,
    DriverUnmappingInvalidView,
    DriverUsedExcessivePtes,
    LockedPagesTrackerCorruption,
    SystemPteMisuse,
    DriverCorruptedSysptes,
    DriverInvalidStackAccess,
    PoolCorruptionInFileArea,
    ImpersonatingWorkerThread,
    AcpiBiosFatalError,
    WorkerThreadReturnedAtBadIrql,
    ManuallyInitiatedCrash,
    ResourceNotOwned,
    WorkerInvalid,
    DriverVerifierDmaViolation,
    InvalidFloatingPointState,
    InvalidCancelOfFileOpen,
    ActiveExWorkerThreadTermination,
    ThreadStuckInDeviceDriver,
    DirtyMappedPagesCongestion,
    SessionHasValidSpecialPoolOnExit,
    UnmountableBootVolume,
    CriticalProcessDied,
    StorageMiniportError,
    ScsiVerifierDetectedViolation,
    HardwareInterruptStorm,
    DisorderlyShutdown,
    CriticalObjectTermination,
    FltmgrFileSystem,
    PciVerifierDetectedViolation,
    DriverOverranStackBuffer,
    RamdiskBootInitializationFailed,
    DriverReturnedStatusReparseForVolumeOpen,
    HttpDriverCorrupted,
    AttemptedExecuteOfNoexecuteMemory,
    DirtyNowritePagesCongestion,
    BugcodeUsbDriver,
    ReserveQueueOverflow,
    LoaderBlockMismatch,
    ClockWatchdogTimeout,
    DpcWatchdogTimeout,
    MupFileSystem,
    AgpInvalidAccess,
    AgpGartCorruption,
    AgpIllegallyReprogrammed,
    ThirdPartyFileSystemFailure,
    CriticalStructureCorruption,
    AppTaggingInitializationFailed,
    FsrtlExtraCreateParameterViolation,
    WdfViolation,
    VideoMemoryManagementInternal,
    ResourceManagerExceptionNotHandled,
    RecursiveNmi,
    MsrpcStateViolation,
    VideoDxgkrnlFatalError,
    VideoShadowDriverFatalError,
    AgpInternal,
    VideoTdrFailure,
    VideoTdrTimeoutDetected,
    VideoSchedulerInternalError,
    EmInitializationFailure,
    DriverReturnedHoldingCancelLock,
    AttemptedWriteToCmProtectedStorage,
    EventTracingFatalError,
    TooManyRecursiveFaults,
    InvalidDriverHandle,
    BitlockerFatalError,
    DriverViolation,
    WheaInternalError,
    CryptoSelfTestFailure,
    WheaUncorrectableError,
    NmrInvalidState,
    NetioInvalidPoolCaller,
    PageNotZero,
    WorkerThreadReturnedWithBadIoPriority,
    WorkerThreadReturnedWithBadPagingIoPriority,
    MuiNoValidSystemLanguage,
    FaultyHardwareCorruptedPage,
    ExfatFileSystem,
    VolsnapOverlappedTableAccess,
    InvalidMdlRange,
    VhdBootInitializationFailed,
    DynamicAddProcessorMismatch,
    InvalidExtendedProcessorState,
    ResourceOwnerPointerInvalid,
    DpcWatchdogViolation,
    DriveExtender,
    RegistryFilterDriverException,
    VhdBootHostVolumeNotEnoughSpace,
    Win32kHandleManager,
    GpioControllerDriverError,
    KernelSecurityCheckFailure,
    KernelModeHeapCorruption,
    PassiveInterruptError,
    InvalidIoBoostState,
    CriticalInitializationFailure,
    StorageDeviceAbnormalityDetected,
    ProcessorDriverInternal,
    BugcodeUsb3Driver,
    SecureBootViolation,
    AbnormalResetDetected,
    RefsFileSystem,
    KernelWmiInternal,
    SocSubsystemFailure,
    FatalAbnormalResetError,
    ExceptionScopeInvalid,
    SocCriticalDeviceRemoved,
    PdcWatchdogTimeout,
    TcpipAoacNicActiveReferenceLeak,
    UnsupportedInstructionMode,
    InvalidPushLockFlags,
    KernelLockEntryLeakedOnThreadTermination,
    UnexpectedStoreException,
    OsDataTampering,
    KernelThreadPriorityFloorViolation,
    IllegalIommuPageFault,
    HalIllegalIommuPageFault,
    SdbusInternalError,
    WorkerThreadReturnedWithSystemPagePriorityActive,
    Win32kAtomicCheckFailure,
    KernelAutoBoostInvalidLockRelease,
    WorkerThreadTestCondition,
    Win32kCriticalFailure,
    InvalidRundownProtectionFlags,
    InvalidSlotAllocatorFlags,
    EresourceInvalidRelease,
    ClusterCsvClussvcDisconnectWatchdog,
    CryptoLibraryInternalError,
    CoremsgcallInternalError,
    CoremsgInternalError,
    ElamDriverDetectedFatalError,
    ProfilerConfigurationIllegal,
    MicrocodeRevisionMismatch,
    VideoDwminitTimeoutFallbackBdd,
    BadObjectHeader,
    SecureKernelError,
    HyperguardViolation,
    SecureFaultUnhandled,
    KernelPartitionReferenceViolation,
    PfDetectedCorruption,
    KernelAutoBoostLockAcquisitionWithRaisedIrql,
    LoaderRollbackDetected,
    Win32kSecurityFailure,
    KernelStorageSlotInUse,
    WorkerThreadReturnedWhileAttachedToSilo,
    TtmFatalError,
    Win32kPowerWatchdogTimeout,
    TtmWatchdogTimeout,
    Win32kCalloutWatchdogBugcheck,
    ExceptionOnInvalidStack,
    UnwindOnInvalidStack,
    FastEresourcePreconditionViolation,
    StoreDataStructureCorruption,
    ManuallyInitiatedPowerButtonHold,
    SyntheticWatchdogTimeout,
    InvalidSiloDetach,
    InvalidCallbackStackAddress,
    InvalidKernelStackAddress,
    HardwareWatchdogTimeout,
    CpiFirmwareWatchdogTimeout,
    WorkerThreadInvalidState,
    WfpInvalidOperation,
    DriverPnpWatchdog,
    WorkerThreadReturnedWithNonDefaultWorkloadClass,
    EfsFatalError,
    UcmucsiFailure,
    HalIommuInternalError,
    HalBlockedProcessorInternalError,
    IpiWatchdogTimeout,
    DmaCommonBufferVectorError,
    BugcodeMbbadapterDriver,
    BugcodeWifiadapterDriver,
    ProcessorStartTimeout,
    VideoDxgkrnlSysmmFatalError,
    IllegalAtsInitialization,
    SecurePciConfigSpaceAccessViolation,
    DamWatchdogTimeout,
    HandleErrorOnCriticalThread,
    KasanEnlightenmentViolation,
    KasanIllegalAccess,
    XboxEractrlCsTimeout,
    BcBluetoothVerifierFault,
    BcBthminiVerifierFault,
    HypervisorError,
    SystemThreadExceptionNotHandledM,
    UnexpectedKernelModeTrapM,
    KernelModeExceptionNotHandledM,
    ThreadStuckInDeviceDriverM,
    ThreadTerminateHeldMutex,
    StatusCannotLoadRegistryFile,
    WinlogonFatalError,
    StatusImageChecksumMismatch,
    ManuallyInitiatedCrash1,
}

impl ErrorTypeEnum {
    pub fn as_str(&self) -> &'static str {
        match self {
            ErrorTypeEnum::ApcIndexMismatch => "APC_INDEX_MISMATCH",
            ErrorTypeEnum::DeviceQueueNotBusy => "DEVICE_QUEUE_NOT_BUSY",
            ErrorTypeEnum::InvalidAffinitySet => "INVALID_AFFINITY_SET",
            ErrorTypeEnum::InvalidDataAccessTrap => "INVALID_DATA_ACCESS_TRAP",
            ErrorTypeEnum::InvalidProcessAttachAttempt => "INVALID_PROCESS_ATTACH_ATTEMPT",
            ErrorTypeEnum::InvalidProcessDetachAttempt => "INVALID_PROCESS_DETACH_ATTEMPT",
            ErrorTypeEnum::InvalidSoftwareInterrupt => "INVALID_SOFTWARE_INTERRUPT",
            ErrorTypeEnum::IrqlNotDispatchLevel => "IRQL_NOT_DISPATCH_LEVEL",
            ErrorTypeEnum::IrqlNotGreaterOrEqual => "IRQL_NOT_GREATER_OR_EQUAL",
            ErrorTypeEnum::IrqlNotLessOrEqual => "IRQL_NOT_LESS_OR_EQUAL",
            ErrorTypeEnum::NoExceptionHandlingSupport => "NO_EXCEPTION_HANDLING_SUPPORT",
            ErrorTypeEnum::MaximumWaitObjectsExceeded => "MAXIMUM_WAIT_OBJECTS_EXCEEDED",
            ErrorTypeEnum::MutexLevelNumberViolation => "MUTEX_LEVEL_NUMBER_VIOLATION",
            ErrorTypeEnum::NoUserModeContext => "NO_USER_MODE_CONTEXT",
            ErrorTypeEnum::SpinLockAlreadyOwned => "SPIN_LOCK_ALREADY_OWNED",
            ErrorTypeEnum::SpinLockNotOwned => "SPIN_LOCK_NOT_OWNED",
            ErrorTypeEnum::ThreadNotMutexOwner => "THREAD_NOT_MUTEX_OWNER",
            ErrorTypeEnum::TrapCauseUnknown => "TRAP_CAUSE_UNKNOWN",
            ErrorTypeEnum::EmptyThreadReaperList => "EMPTY_THREAD_REAPER_LIST",
            ErrorTypeEnum::CreateDeleteLockNotLocked => "CREATE_DELETE_LOCK_NOT_LOCKED",
            ErrorTypeEnum::LastChanceCalledFromKmode => "LAST_CHANCE_CALLED_FROM_KMODE",
            ErrorTypeEnum::CidHandleCreation => "CID_HANDLE_CREATION",
            ErrorTypeEnum::CidHandleDeletion => "CID_HANDLE_DELETION",
            ErrorTypeEnum::ReferenceByPointer => "REFERENCE_BY_POINTER",
            ErrorTypeEnum::BadPoolHeader => "BAD_POOL_HEADER",
            ErrorTypeEnum::MemoryManagement => "MEMORY_MANAGEMENT",
            ErrorTypeEnum::PfnShareCount => "PFN_SHARE_COUNT",
            ErrorTypeEnum::PfnReferenceCount => "PFN_REFERENCE_COUNT",
            ErrorTypeEnum::NoSpinLockAvailable => "NO_SPIN_LOCK_AVAILABLE",
            ErrorTypeEnum::KmodeExceptionNotHandled => "KMODE_EXCEPTION_NOT_HANDLED",
            ErrorTypeEnum::SharedResourceConvError => "SHARED_RESOURCE_CONV_ERROR",
            ErrorTypeEnum::KernelApcPendingDuringExit => "KERNEL_APC_PENDING_DURING_EXIT",
            ErrorTypeEnum::QuotaUnderflow => "QUOTA_UNDERFLOW",
            ErrorTypeEnum::FileSystem => "FILE_SYSTEM",
            ErrorTypeEnum::FatFileSystem => "FAT_FILE_SYSTEM",
            ErrorTypeEnum::NtfsFileSystem => "NTFS_FILE_SYSTEM",
            ErrorTypeEnum::NpfsFileSystem => "NPFS_FILE_SYSTEM",
            ErrorTypeEnum::CdfsFileSystem => "CDFS_FILE_SYSTEM",
            ErrorTypeEnum::RdrFileSystem => "RDR_FILE_SYSTEM",
            ErrorTypeEnum::CorruptAccessToken => "CORRUPT_ACCESS_TOKEN",
            ErrorTypeEnum::SecuritySystem => "SECURITY_SYSTEM",
            ErrorTypeEnum::InconsistentIrp => "INCONSISTENT_IRP",
            ErrorTypeEnum::PanicStackSwitch => "PANIC_STACK_SWITCH",
            ErrorTypeEnum::PortDriverInternal => "PORT_DRIVER_INTERNAL",
            ErrorTypeEnum::ScsiDiskDriverInternal => "SCSI_DISK_DRIVER_INTERNAL",
            ErrorTypeEnum::DataBusError => "DATA_BUS_ERROR",
            ErrorTypeEnum::InstructionBusError => "INSTRUCTION_BUS_ERROR",
            ErrorTypeEnum::SetOfInvalidContext => "SET_OF_INVALID_CONTEXT",
            ErrorTypeEnum::Phase0InitializationFailed => "PHASE0_INITIALIZATION_FAILED",
            ErrorTypeEnum::Phase1InitializationFailed => "PHASE1_INITIALIZATION_FAILED",
            ErrorTypeEnum::UnexpectedInitializationCall => "UNEXPECTED_INITIALIZATION_CALL",
            ErrorTypeEnum::CacheManager => "CACHE_MANAGER",
            ErrorTypeEnum::NoMoreIrpStackLocations => "NO_MORE_IRP_STACK_LOCATIONS",
            ErrorTypeEnum::DeviceReferenceCountNotZero => "DEVICE_REFERENCE_COUNT_NOT_ZERO",
            ErrorTypeEnum::FloppyInternalError => "FLOPPY_INTERNAL_ERROR",
            ErrorTypeEnum::SerialDriverInternal => "SERIAL_DRIVER_INTERNAL",
            ErrorTypeEnum::SystemExitOwnedMutex => "SYSTEM_EXIT_OWNED_MUTEX",
            ErrorTypeEnum::SystemUnwindPreviousUser => "SYSTEM_UNWIND_PREVIOUS_USER",
            ErrorTypeEnum::SystemServiceException => "SYSTEM_SERVICE_EXCEPTION",
            ErrorTypeEnum::InterruptUnwindAttempted => "INTERRUPT_UNWIND_ATTEMPTED",
            ErrorTypeEnum::InterruptExceptionNotHandled => "INTERRUPT_EXCEPTION_NOT_HANDLED",
            ErrorTypeEnum::MultiprocessorConfigurationNotSupported => {
                "MULTIPROCESSOR_CONFIGURATION_NOT_SUPPORTED"
            }
            ErrorTypeEnum::NoMoreSystemPtes => "NO_MORE_SYSTEM_PTES",
            ErrorTypeEnum::TargetMdlTooSmall => "TARGET_MDL_TOO_SMALL",
            ErrorTypeEnum::MustSucceedPoolEmpty => "MUST_SUCCEED_POOL_EMPTY",
            ErrorTypeEnum::AtdiskDriverInternal => "ATDISK_DRIVER_INTERNAL",
            ErrorTypeEnum::NoSuchPartition => "NO_SUCH_PARTITION",
            ErrorTypeEnum::MultipleIrpCompleteRequests => "MULTIPLE_IRP_COMPLETE_REQUESTS",
            ErrorTypeEnum::InsufficientSystemMapRegs => "INSUFFICIENT_SYSTEM_MAP_REGS",
            ErrorTypeEnum::DerefUnknownLogonSession => "DEREF_UNKNOWN_LOGON_SESSION",
            ErrorTypeEnum::RefUnknownLogonSession => "REF_UNKNOWN_LOGON_SESSION",
            ErrorTypeEnum::CancelStateInCompletedIrp => "CANCEL_STATE_IN_COMPLETED_IRP",
            ErrorTypeEnum::PageFaultWithInterruptsOff => "PAGE_FAULT_WITH_INTERRUPTS_OFF",
            ErrorTypeEnum::IrqlGtZeroAtSystemService => "IRQL_GT_ZERO_AT_SYSTEM_SERVICE",
            ErrorTypeEnum::StreamsInternalError => "STREAMS_INTERNAL_ERROR",
            ErrorTypeEnum::FatalUnhandledHardError => "FATAL_UNHANDLED_HARD_ERROR",
            ErrorTypeEnum::NoPagesAvailable => "NO_PAGES_AVAILABLE",
            ErrorTypeEnum::PfnListCorrupt => "PFN_LIST_CORRUPT",
            ErrorTypeEnum::NdisInternalError => "NDIS_INTERNAL_ERROR",
            ErrorTypeEnum::PageFaultInNonpagedArea => "PAGE_FAULT_IN_NONPAGED_AREA",
            ErrorTypeEnum::RegistryError => "REGISTRY_ERROR",
            ErrorTypeEnum::MailslotFileSystem => "MAILSLOT_FILE_SYSTEM",
            ErrorTypeEnum::NoBootDevice => "NO_BOOT_DEVICE",
            ErrorTypeEnum::LmServerInternalError => "LM_SERVER_INTERNAL_ERROR",
            ErrorTypeEnum::DataCoherencyException => "DATA_COHERENCY_EXCEPTION",
            ErrorTypeEnum::InstructionCoherencyException => "INSTRUCTION_COHERENCY_EXCEPTION",
            ErrorTypeEnum::XnsInternalError => "XNS_INTERNAL_ERROR",
            ErrorTypeEnum::FtdiskInternalError => "FTDISK_INTERNAL_ERROR",
            ErrorTypeEnum::PinballFileSystem => "PINBALL_FILE_SYSTEM",
            ErrorTypeEnum::CriticalServiceFailed => "CRITICAL_SERVICE_FAILED",
            ErrorTypeEnum::SetEnvVarFailed => "SET_ENV_VAR_FAILED",
            ErrorTypeEnum::HalInitializationFailed => "HAL_INITIALIZATION_FAILED",
            ErrorTypeEnum::UnsupportedProcessor => "UNSUPPORTED_PROCESSOR",
            ErrorTypeEnum::ObjectInitializationFailed => "OBJECT_INITIALIZATION_FAILED",
            ErrorTypeEnum::SecurityInitializationFailed => "SECURITY_INITIALIZATION_FAILED",
            ErrorTypeEnum::ProcessInitializationFailed => "PROCESS_INITIALIZATION_FAILED",
            ErrorTypeEnum::Hal1InitializationFailed => "HAL1_INITIALIZATION_FAILED",
            ErrorTypeEnum::Object1InitializationFailed => "OBJECT1_INITIALIZATION_FAILED",
            ErrorTypeEnum::Security1InitializationFailed => "SECURITY1_INITIALIZATION_FAILED",
            ErrorTypeEnum::SymbolicInitializationFailed => "SYMBOLIC_INITIALIZATION_FAILED",
            ErrorTypeEnum::Memory1InitializationFailed => "MEMORY1_INITIALIZATION_FAILED",
            ErrorTypeEnum::CacheInitializationFailed => "CACHE_INITIALIZATION_FAILED",
            ErrorTypeEnum::ConfigInitializationFailed => "CONFIG_INITIALIZATION_FAILED",
            ErrorTypeEnum::FileInitializationFailed => "FILE_INITIALIZATION_FAILED",
            ErrorTypeEnum::Io1InitializationFailed => "IO1_INITIALIZATION_FAILED",
            ErrorTypeEnum::LpcInitializationFailed => "LPC_INITIALIZATION_FAILED",
            ErrorTypeEnum::Process1InitializationFailed => "PROCESS1_INITIALIZATION_FAILED",
            ErrorTypeEnum::RefmonInitializationFailed => "REFMON_INITIALIZATION_FAILED",
            ErrorTypeEnum::Session1InitializationFailed => "SESSION1_INITIALIZATION_FAILED",
            ErrorTypeEnum::Session2InitializationFailed => "SESSION2_INITIALIZATION_FAILED",
            ErrorTypeEnum::Session3InitializationFailed => "SESSION3_INITIALIZATION_FAILED",
            ErrorTypeEnum::Session4InitializationFailed => "SESSION4_INITIALIZATION_FAILED",
            ErrorTypeEnum::Session5InitializationFailed => "SESSION5_INITIALIZATION_FAILED",
            ErrorTypeEnum::AssignDriveLettersFailed => "ASSIGN_DRIVE_LETTERS_FAILED",
            ErrorTypeEnum::ConfigListFailed => "CONFIG_LIST_FAILED",
            ErrorTypeEnum::BadSystemConfigInfo => "BAD_SYSTEM_CONFIG_INFO",
            ErrorTypeEnum::CannotWriteConfiguration => "CANNOT_WRITE_CONFIGURATION",
            ErrorTypeEnum::ProcessHasLockedPages => "PROCESS_HAS_LOCKED_PAGES",
            ErrorTypeEnum::KernelStackInpageError => "KERNEL_STACK_INPAGE_ERROR",
            ErrorTypeEnum::Phase0Exception => "PHASE0_EXCEPTION",
            ErrorTypeEnum::MismatchedHal => "MISMATCHED_HAL",
            ErrorTypeEnum::KernelDataInpageError => "KERNEL_DATA_INPAGE_ERROR",
            ErrorTypeEnum::InaccessibleBootDevice => "INACCESSIBLE_BOOT_DEVICE",
            ErrorTypeEnum::BugcodeNdisDriver => "BUGCODE_NDIS_DRIVER",
            ErrorTypeEnum::InstallMoreMemory => "INSTALL_MORE_MEMORY",
            ErrorTypeEnum::SystemThreadExceptionNotHandled => "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED",
            ErrorTypeEnum::UnexpectedKernelModeTrap => "UNEXPECTED_KERNEL_MODE_TRAP",
            ErrorTypeEnum::NmiHardwareFailure => "NMI_HARDWARE_FAILURE",
            ErrorTypeEnum::SpinLockInitFailure => "SPIN_LOCK_INIT_FAILURE",
            ErrorTypeEnum::DfsFileSystem => "DFS_FILE_SYSTEM",
            ErrorTypeEnum::SetupFailure => "SETUP_FAILURE",
            ErrorTypeEnum::MbrChecksumMismatch => "MBR_CHECKSUM_MISMATCH",
            ErrorTypeEnum::KernelModeExceptionNotHandled => "KERNEL_MODE_EXCEPTION_NOT_HANDLED",
            ErrorTypeEnum::Pp0InitializationFailed => "PP0_INITIALIZATION_FAILED",
            ErrorTypeEnum::Pp1InitializationFailed => "PP1_INITIALIZATION_FAILED",
            ErrorTypeEnum::UpDriverOnMpSystem => "UP_DRIVER_ON_MP_SYSTEM",
            ErrorTypeEnum::InvalidKernelHandle => "INVALID_KERNEL_HANDLE",
            ErrorTypeEnum::KernelStackLockedAtExit => "KERNEL_STACK_LOCKED_AT_EXIT",
            ErrorTypeEnum::InvalidWorkQueueItem => "INVALID_WORK_QUEUE_ITEM",
            ErrorTypeEnum::BoundImageUnsupported => "BOUND_IMAGE_UNSUPPORTED",
            ErrorTypeEnum::EndOfNtEvaluationPeriod => "END_OF_NT_EVALUATION_PERIOD",
            ErrorTypeEnum::InvalidRegionOrSegment => "INVALID_REGION_OR_SEGMENT",
            ErrorTypeEnum::SystemLicenseViolation => "SYSTEM_LICENSE_VIOLATION",
            ErrorTypeEnum::UdfsFileSystem => "UDFS_FILE_SYSTEM",
            ErrorTypeEnum::MachineCheckException => "MACHINE_CHECK_EXCEPTION",
            ErrorTypeEnum::UserModeHealthMonitor => "USER_MODE_HEALTH_MONITOR",
            ErrorTypeEnum::DriverPowerStateFailure => "DRIVER_POWER_STATE_FAILURE",
            ErrorTypeEnum::InternalPowerError => "INTERNAL_POWER_ERROR",
            ErrorTypeEnum::PciBusDriverInternal => "PCI_BUS_DRIVER_INTERNAL",
            ErrorTypeEnum::MemoryImageCorrupt => "MEMORY_IMAGE_CORRUPT",
            ErrorTypeEnum::AcpiDriverInternal => "ACPI_DRIVER_INTERNAL",
            ErrorTypeEnum::CnssFileSystemFilter => "CNSS_FILE_SYSTEM_FILTER",
            ErrorTypeEnum::AcpiBiosError => "ACPI_BIOS_ERROR",
            ErrorTypeEnum::BadExhandle => "BAD_EXHANDLE",
            ErrorTypeEnum::HalMemoryAllocation => "HAL_MEMORY_ALLOCATION",
            ErrorTypeEnum::VideoDriverDebugReportRequest => "VIDEO_DRIVER_DEBUG_REPORT_REQUEST",
            ErrorTypeEnum::BgiDetectedViolation => "BGI_DETECTED_VIOLATION",
            ErrorTypeEnum::VideoDriverInitFailure => "VIDEO_DRIVER_INIT_FAILURE",
            ErrorTypeEnum::AttemptedSwitchFromDpc => "ATTEMPTED_SWITCH_FROM_DPC",
            ErrorTypeEnum::ChipsetDetectedError => "CHIPSET_DETECTED_ERROR",
            ErrorTypeEnum::SessionHasValidViewsOnExit => "SESSION_HAS_VALID_VIEWS_ON_EXIT",
            ErrorTypeEnum::NetworkBootInitializationFailed => "NETWORK_BOOT_INITIALIZATION_FAILED",
            ErrorTypeEnum::NetworkBootDuplicateAddress => "NETWORK_BOOT_DUPLICATE_ADDRESS",
            ErrorTypeEnum::InvalidHibernatedState => "INVALID_HIBERNATED_STATE",
            ErrorTypeEnum::AttemptedWriteToReadonlyMemory => "ATTEMPTED_WRITE_TO_READONLY_MEMORY",
            ErrorTypeEnum::MutexAlreadyOwned => "MUTEX_ALREADY_OWNED",
            ErrorTypeEnum::SpecialPoolDetectedMemoryCorruption => {
                "SPECIAL_POOL_DETECTED_MEMORY_CORRUPTION"
            }
            ErrorTypeEnum::BadPoolCaller => "BAD_POOL_CALLER",
            ErrorTypeEnum::DriverVerifierDetectedViolation => "DRIVER_VERIFIER_DETECTED_VIOLATION",
            ErrorTypeEnum::DriverCorruptedExpool => "DRIVER_CORRUPTED_EXPOOL",
            ErrorTypeEnum::DriverCaughtModifyingFreedPool => "DRIVER_CAUGHT_MODIFYING_FREED_POOL",
            ErrorTypeEnum::TimerOrDpcInvalid => "TIMER_OR_DPC_INVALID",
            ErrorTypeEnum::IrqlUnexpectedValue => "IRQL_UNEXPECTED_VALUE",
            ErrorTypeEnum::DriverVerifierIomanagerViolation => {
                "DRIVER_VERIFIER_IOMANAGER_VIOLATION"
            }
            ErrorTypeEnum::PnpDetectedFatalError => "PNP_DETECTED_FATAL_ERROR",
            ErrorTypeEnum::DriverLeftLockedPagesInProcess => "DRIVER_LEFT_LOCKED_PAGES_IN_PROCESS",
            ErrorTypeEnum::PageFaultInFreedSpecialPool => "PAGE_FAULT_IN_FREED_SPECIAL_POOL",
            ErrorTypeEnum::PageFaultBeyondEndOfAllocation => "PAGE_FAULT_BEYOND_END_OF_ALLOCATION",
            ErrorTypeEnum::DriverUnloadedWithoutCancellingPendingOperations => {
                "DRIVER_UNLOADED_WITHOUT_CANCELLING_PENDING_OPERATIONS"
            }
            ErrorTypeEnum::TerminalServerDriverMadeIncorrectMemoryReference => {
                "TERMINAL_SERVER_DRIVER_MADE_INCORRECT_MEMORY_REFERENCE"
            }
            ErrorTypeEnum::DriverCorruptedMmpool => "DRIVER_CORRUPTED_MMPOOL",
            ErrorTypeEnum::DriverIrqlNotLessOrEqual => "DRIVER_IRQL_NOT_LESS_OR_EQUAL",
            ErrorTypeEnum::BugcodeIdDriver => "BUGCODE_ID_DRIVER",
            ErrorTypeEnum::DriverPortionMustBeNonpaged => "DRIVER_PORTION_MUST_BE_NONPAGED",
            ErrorTypeEnum::SystemScanAtRaisedIrqlCaughtImproperDriverUnload => {
                "SYSTEM_SCAN_AT_RAISED_IRQL_CAUGHT_IMPROPER_DRIVER_UNLOAD"
            }
            ErrorTypeEnum::DriverPageFaultInFreedSpecialPool => {
                "DRIVER_PAGE_FAULT_IN_FREED_SPECIAL_POOL"
            }
            ErrorTypeEnum::DriverPageFaultBeyondEndOfAllocation => {
                "DRIVER_PAGE_FAULT_BEYOND_END_OF_ALLOCATION"
            }
            ErrorTypeEnum::DriverUnmappingInvalidView => "DRIVER_UNMAPPING_INVALID_VIEW",
            ErrorTypeEnum::DriverUsedExcessivePtes => "DRIVER_USED_EXCESSIVE_PTES",
            ErrorTypeEnum::LockedPagesTrackerCorruption => "LOCKED_PAGES_TRACKER_CORRUPTION",
            ErrorTypeEnum::SystemPteMisuse => "SYSTEM_PTE_MISUSE",
            ErrorTypeEnum::DriverCorruptedSysptes => "DRIVER_CORRUPTED_SYSPTES",
            ErrorTypeEnum::DriverInvalidStackAccess => "DRIVER_INVALID_STACK_ACCESS",
            ErrorTypeEnum::PoolCorruptionInFileArea => "POOL_CORRUPTION_IN_FILE_AREA",
            ErrorTypeEnum::ImpersonatingWorkerThread => "IMPERSONATING_WORKER_THREAD",
            ErrorTypeEnum::AcpiBiosFatalError => "ACPI_BIOS_FATAL_ERROR",
            ErrorTypeEnum::WorkerThreadReturnedAtBadIrql => "WORKER_THREAD_RETURNED_AT_BAD_IRQL",
            ErrorTypeEnum::ManuallyInitiatedCrash => "MANUALLY_INITIATED_CRASH",
            ErrorTypeEnum::ResourceNotOwned => "RESOURCE_NOT_OWNED",
            ErrorTypeEnum::WorkerInvalid => "WORKER_INVALID",
            ErrorTypeEnum::DriverVerifierDmaViolation => "DRIVER_VERIFIER_DMA_VIOLATION",
            ErrorTypeEnum::InvalidFloatingPointState => "INVALID_FLOATING_POINT_STATE",
            ErrorTypeEnum::InvalidCancelOfFileOpen => "INVALID_CANCEL_OF_FILE_OPEN",
            ErrorTypeEnum::ActiveExWorkerThreadTermination => "ACTIVE_EX_WORKER_THREAD_TERMINATION",
            ErrorTypeEnum::ThreadStuckInDeviceDriver => "THREAD_STUCK_IN_DEVICE_DRIVER",
            ErrorTypeEnum::DirtyMappedPagesCongestion => "DIRTY_MAPPED_PAGES_CONGESTION",
            ErrorTypeEnum::SessionHasValidSpecialPoolOnExit => {
                "SESSION_HAS_VALID_SPECIAL_POOL_ON_EXIT"
            }
            ErrorTypeEnum::UnmountableBootVolume => "UNMOUNTABLE_BOOT_VOLUME",
            ErrorTypeEnum::CriticalProcessDied => "CRITICAL_PROCESS_DIED",
            ErrorTypeEnum::StorageMiniportError => "STORAGE_MINIPORT_ERROR",
            ErrorTypeEnum::ScsiVerifierDetectedViolation => "SCSI_VERIFIER_DETECTED_VIOLATION",
            ErrorTypeEnum::HardwareInterruptStorm => "HARDWARE_INTERRUPT_STORM",
            ErrorTypeEnum::DisorderlyShutdown => "DISORDERLY_SHUTDOWN",
            ErrorTypeEnum::CriticalObjectTermination => "CRITICAL_OBJECT_TERMINATION",
            ErrorTypeEnum::FltmgrFileSystem => "FLTMGR_FILE_SYSTEM",
            ErrorTypeEnum::PciVerifierDetectedViolation => "PCI_VERIFIER_DETECTED_VIOLATION",
            ErrorTypeEnum::DriverOverranStackBuffer => "DRIVER_OVERRAN_STACK_BUFFER",
            ErrorTypeEnum::RamdiskBootInitializationFailed => "RAMDISK_BOOT_INITIALIZATION_FAILED",
            ErrorTypeEnum::DriverReturnedStatusReparseForVolumeOpen => {
                "DRIVER_RETURNED_STATUS_REPARSE_FOR_VOLUME_OPEN"
            }
            ErrorTypeEnum::HttpDriverCorrupted => "HTTP_DRIVER_CORRUPTED",
            ErrorTypeEnum::AttemptedExecuteOfNoexecuteMemory => {
                "ATTEMPTED_EXECUTE_OF_NOEXECUTE_MEMORY"
            }
            ErrorTypeEnum::DirtyNowritePagesCongestion => "DIRTY_NOWRITE_PAGES_CONGESTION",
            ErrorTypeEnum::BugcodeUsbDriver => "BUGCODE_USB_DRIVER",
            ErrorTypeEnum::ReserveQueueOverflow => "RESERVE_QUEUE_OVERFLOW",
            ErrorTypeEnum::LoaderBlockMismatch => "LOADER_BLOCK_MISMATCH",
            ErrorTypeEnum::ClockWatchdogTimeout => "CLOCK_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::DpcWatchdogTimeout => "DPC_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::MupFileSystem => "MUP_FILE_SYSTEM",
            ErrorTypeEnum::AgpInvalidAccess => "AGP_INVALID_ACCESS",
            ErrorTypeEnum::AgpGartCorruption => "AGP_GART_CORRUPTION",
            ErrorTypeEnum::AgpIllegallyReprogrammed => "AGP_ILLEGALLY_REPROGRAMMED",
            ErrorTypeEnum::ThirdPartyFileSystemFailure => "THIRD_PARTY_FILE_SYSTEM_FAILURE",
            ErrorTypeEnum::CriticalStructureCorruption => "CRITICAL_STRUCTURE_CORRUPTION",
            ErrorTypeEnum::AppTaggingInitializationFailed => "APP_TAGGING_INITIALIZATION_FAILED",
            ErrorTypeEnum::FsrtlExtraCreateParameterViolation => {
                "FSRTL_EXTRA_CREATE_PARAMETER_VIOLATION"
            }
            ErrorTypeEnum::WdfViolation => "WDF_VIOLATION",
            ErrorTypeEnum::VideoMemoryManagementInternal => "VIDEO_MEMORY_MANAGEMENT_INTERNAL",
            ErrorTypeEnum::ResourceManagerExceptionNotHandled => {
                "RESOURCE_MANAGER_EXCEPTION_NOT_HANDLED"
            }
            ErrorTypeEnum::RecursiveNmi => "RECURSIVE_NMI",
            ErrorTypeEnum::MsrpcStateViolation => "MSRPC_STATE_VIOLATION",
            ErrorTypeEnum::VideoDxgkrnlFatalError => "VIDEO_DXGKRNL_FATAL_ERROR",
            ErrorTypeEnum::VideoShadowDriverFatalError => "VIDEO_SHADOW_DRIVER_FATAL_ERROR",
            ErrorTypeEnum::AgpInternal => "AGP_INTERNAL",
            ErrorTypeEnum::VideoTdrFailure => "VIDEO_TDR_FAILURE",
            ErrorTypeEnum::VideoTdrTimeoutDetected => "VIDEO_TDR_TIMEOUT_DETECTED",
            ErrorTypeEnum::VideoSchedulerInternalError => "VIDEO_SCHEDULER_INTERNAL_ERROR",
            ErrorTypeEnum::EmInitializationFailure => "EM_INITIALIZATION_FAILURE",
            ErrorTypeEnum::DriverReturnedHoldingCancelLock => "DRIVER_RETURNED_HOLDING_CANCEL_LOCK",
            ErrorTypeEnum::AttemptedWriteToCmProtectedStorage => {
                "ATTEMPTED_WRITE_TO_CM_PROTECTED_STORAGE"
            }
            ErrorTypeEnum::EventTracingFatalError => "EVENT_TRACING_FATAL_ERROR",
            ErrorTypeEnum::TooManyRecursiveFaults => "TOO_MANY_RECURSIVE_FAULTS",
            ErrorTypeEnum::InvalidDriverHandle => "INVALID_DRIVER_HANDLE",
            ErrorTypeEnum::BitlockerFatalError => "BITLOCKER_FATAL_ERROR",
            ErrorTypeEnum::DriverViolation => "DRIVER_VIOLATION",
            ErrorTypeEnum::WheaInternalError => "WHEA_INTERNAL_ERROR",
            ErrorTypeEnum::CryptoSelfTestFailure => "CRYPTO_SELF_TEST_FAILURE",
            ErrorTypeEnum::WheaUncorrectableError => "WHEA_UNCORRECTABLE_ERROR",
            ErrorTypeEnum::NmrInvalidState => "NMR_INVALID_STATE",
            ErrorTypeEnum::NetioInvalidPoolCaller => "NETIO_INVALID_POOL_CALLER",
            ErrorTypeEnum::PageNotZero => "PAGE_NOT_ZERO",
            ErrorTypeEnum::WorkerThreadReturnedWithBadIoPriority => {
                "WORKER_THREAD_RETURNED_WITH_BAD_IO_PRIORITY"
            }
            ErrorTypeEnum::WorkerThreadReturnedWithBadPagingIoPriority => {
                "WORKER_THREAD_RETURNED_WITH_BAD_PAGING_IO_PRIORITY"
            }
            ErrorTypeEnum::MuiNoValidSystemLanguage => "MUI_NO_VALID_SYSTEM_LANGUAGE",
            ErrorTypeEnum::FaultyHardwareCorruptedPage => "FAULTY_HARDWARE_CORRUPTED_PAGE",
            ErrorTypeEnum::ExfatFileSystem => "EXFAT_FILE_SYSTEM",
            ErrorTypeEnum::VolsnapOverlappedTableAccess => "VOLSNAP_OVERLAPPED_TABLE_ACCESS",
            ErrorTypeEnum::InvalidMdlRange => "INVALID_MDL_RANGE",
            ErrorTypeEnum::VhdBootInitializationFailed => "VHD_BOOT_INITIALIZATION_FAILED",
            ErrorTypeEnum::DynamicAddProcessorMismatch => "DYNAMIC_ADD_PROCESSOR_MISMATCH",
            ErrorTypeEnum::InvalidExtendedProcessorState => "INVALID_EXTENDED_PROCESSOR_STATE",
            ErrorTypeEnum::ResourceOwnerPointerInvalid => "RESOURCE_OWNER_POINTER_INVALID",
            ErrorTypeEnum::DpcWatchdogViolation => "DPC_WATCHDOG_VIOLATION",
            ErrorTypeEnum::DriveExtender => "DRIVE_EXTENDER",
            ErrorTypeEnum::RegistryFilterDriverException => "REGISTRY_FILTER_DRIVER_EXCEPTION",
            ErrorTypeEnum::VhdBootHostVolumeNotEnoughSpace => {
                "VHD_BOOT_HOST_VOLUME_NOT_ENOUGH_SPACE"
            }
            ErrorTypeEnum::Win32kHandleManager => "WIN32K_HANDLE_MANAGER",
            ErrorTypeEnum::GpioControllerDriverError => "GPIO_CONTROLLER_DRIVER_ERROR",
            ErrorTypeEnum::KernelSecurityCheckFailure => "KERNEL_SECURITY_CHECK_FAILURE",
            ErrorTypeEnum::KernelModeHeapCorruption => "KERNEL_MODE_HEAP_CORRUPTION",
            ErrorTypeEnum::PassiveInterruptError => "PASSIVE_INTERRUPT_ERROR",
            ErrorTypeEnum::InvalidIoBoostState => "INVALID_IO_BOOST_STATE",
            ErrorTypeEnum::CriticalInitializationFailure => "CRITICAL_INITIALIZATION_FAILURE",
            ErrorTypeEnum::StorageDeviceAbnormalityDetected => {
                "STORAGE_DEVICE_ABNORMALITY_DETECTED"
            }
            ErrorTypeEnum::ProcessorDriverInternal => "PROCESSOR_DRIVER_INTERNAL",
            ErrorTypeEnum::BugcodeUsb3Driver => "BUGCODE_USB3_DRIVER",
            ErrorTypeEnum::SecureBootViolation => "SECURE_BOOT_VIOLATION",
            ErrorTypeEnum::AbnormalResetDetected => "ABNORMAL_RESET_DETECTED",
            ErrorTypeEnum::RefsFileSystem => "REFS_FILE_SYSTEM",
            ErrorTypeEnum::KernelWmiInternal => "KERNEL_WMI_INTERNAL",
            ErrorTypeEnum::SocSubsystemFailure => "SOC_SUBSYSTEM_FAILURE",
            ErrorTypeEnum::FatalAbnormalResetError => "FATAL_ABNORMAL_RESET_ERROR",
            ErrorTypeEnum::ExceptionScopeInvalid => "EXCEPTION_SCOPE_INVALID",
            ErrorTypeEnum::SocCriticalDeviceRemoved => "SOC_CRITICAL_DEVICE_REMOVED",
            ErrorTypeEnum::PdcWatchdogTimeout => "PDC_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::TcpipAoacNicActiveReferenceLeak => {
                "TCPIP_AOAC_NIC_ACTIVE_REFERENCE_LEAK"
            }
            ErrorTypeEnum::UnsupportedInstructionMode => "UNSUPPORTED_INSTRUCTION_MODE",
            ErrorTypeEnum::InvalidPushLockFlags => "INVALID_PUSH_LOCK_FLAGS",
            ErrorTypeEnum::KernelLockEntryLeakedOnThreadTermination => {
                "KERNEL_LOCK_ENTRY_LEAKED_ON_THREAD_TERMINATION"
            }
            ErrorTypeEnum::UnexpectedStoreException => "UNEXPECTED_STORE_EXCEPTION",
            ErrorTypeEnum::OsDataTampering => "OS_DATA_TAMPERING",
            ErrorTypeEnum::KernelThreadPriorityFloorViolation => {
                "KERNEL_THREAD_PRIORITY_FLOOR_VIOLATION"
            }
            ErrorTypeEnum::IllegalIommuPageFault => "ILLEGAL_IOMMU_PAGE_FAULT",
            ErrorTypeEnum::HalIllegalIommuPageFault => "HAL_ILLEGAL_IOMMU_PAGE_FAULT",
            ErrorTypeEnum::SdbusInternalError => "SDBUS_INTERNAL_ERROR",
            ErrorTypeEnum::WorkerThreadReturnedWithSystemPagePriorityActive => {
                "WORKER_THREAD_RETURNED_WITH_SYSTEM_PAGE_PRIORITY_ACTIVE"
            }
            ErrorTypeEnum::Win32kAtomicCheckFailure => "WIN32K_ATOMIC_CHECK_FAILURE",
            ErrorTypeEnum::KernelAutoBoostInvalidLockRelease => {
                "KERNEL_AUTO_BOOST_INVALID_LOCK_RELEASE"
            }
            ErrorTypeEnum::WorkerThreadTestCondition => "WORKER_THREAD_TEST_CONDITION",
            ErrorTypeEnum::Win32kCriticalFailure => "WIN32K_CRITICAL_FAILURE",
            ErrorTypeEnum::InvalidRundownProtectionFlags => "INVALID_RUNDOWN_PROTECTION_FLAGS",
            ErrorTypeEnum::InvalidSlotAllocatorFlags => "INVALID_SLOT_ALLOCATOR_FLAGS",
            ErrorTypeEnum::EresourceInvalidRelease => "ERESOURCE_INVALID_RELEASE",
            ErrorTypeEnum::ClusterCsvClussvcDisconnectWatchdog => {
                "CLUSTER_CSV_CLUSSVC_DISCONNECT_WATCHDOG"
            }
            ErrorTypeEnum::CryptoLibraryInternalError => "CRYPTO_LIBRARY_INTERNAL_ERROR",
            ErrorTypeEnum::CoremsgcallInternalError => "COREMSGCALL_INTERNAL_ERROR",
            ErrorTypeEnum::CoremsgInternalError => "COREMSG_INTERNAL_ERROR",
            ErrorTypeEnum::ElamDriverDetectedFatalError => "ELAM_DRIVER_DETECTED_FATAL_ERROR",
            ErrorTypeEnum::ProfilerConfigurationIllegal => "PROFILER_CONFIGURATION_ILLEGAL",
            ErrorTypeEnum::MicrocodeRevisionMismatch => "MICROCODE_REVISION_MISMATCH",
            ErrorTypeEnum::VideoDwminitTimeoutFallbackBdd => "VIDEO_DWMINIT_TIMEOUT_FALLBACK_BDD",
            ErrorTypeEnum::BadObjectHeader => "BAD_OBJECT_HEADER",
            ErrorTypeEnum::SecureKernelError => "SECURE_KERNEL_ERROR",
            ErrorTypeEnum::HyperguardViolation => "HYPERGUARD_VIOLATION",
            ErrorTypeEnum::SecureFaultUnhandled => "SECURE_FAULT_UNHANDLED",
            ErrorTypeEnum::KernelPartitionReferenceViolation => {
                "KERNEL_PARTITION_REFERENCE_VIOLATION"
            }
            ErrorTypeEnum::PfDetectedCorruption => "PF_DETECTED_CORRUPTION",
            ErrorTypeEnum::KernelAutoBoostLockAcquisitionWithRaisedIrql => {
                "KERNEL_AUTO_BOOST_LOCK_ACQUISITION_WITH_RAISED_IRQL"
            }
            ErrorTypeEnum::LoaderRollbackDetected => "LOADER_ROLLBACK_DETECTED",
            ErrorTypeEnum::Win32kSecurityFailure => "WIN32K_SECURITY_FAILURE",
            ErrorTypeEnum::KernelStorageSlotInUse => "KERNEL_STORAGE_SLOT_IN_USE",
            ErrorTypeEnum::WorkerThreadReturnedWhileAttachedToSilo => {
                "WORKER_THREAD_RETURNED_WHILE_ATTACHED_TO_SILO"
            }
            ErrorTypeEnum::TtmFatalError => "TTM_FATAL_ERROR",
            ErrorTypeEnum::Win32kPowerWatchdogTimeout => "WIN32K_POWER_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::TtmWatchdogTimeout => "TTM_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::Win32kCalloutWatchdogBugcheck => "WIN32K_CALLOUT_WATCHDOG_BUGCHECK",
            ErrorTypeEnum::ExceptionOnInvalidStack => "EXCEPTION_ON_INVALID_STACK",
            ErrorTypeEnum::UnwindOnInvalidStack => "UNWIND_ON_INVALID_STACK",
            ErrorTypeEnum::FastEresourcePreconditionViolation => {
                "FAST_ERESOURCE_PRECONDITION_VIOLATION"
            }
            ErrorTypeEnum::StoreDataStructureCorruption => "STORE_DATA_STRUCTURE_CORRUPTION",
            ErrorTypeEnum::ManuallyInitiatedPowerButtonHold => {
                "MANUALLY_INITIATED_POWER_BUTTON_HOLD"
            }
            ErrorTypeEnum::SyntheticWatchdogTimeout => "SYNTHETIC_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::InvalidSiloDetach => "INVALID_SILO_DETACH",
            ErrorTypeEnum::InvalidCallbackStackAddress => "INVALID_CALLBACK_STACK_ADDRESS",
            ErrorTypeEnum::InvalidKernelStackAddress => "INVALID_KERNEL_STACK_ADDRESS",
            ErrorTypeEnum::HardwareWatchdogTimeout => "HARDWARE_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::CpiFirmwareWatchdogTimeout => "CPI_FIRMWARE_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::WorkerThreadInvalidState => "WORKER_THREAD_INVALID_STATE",
            ErrorTypeEnum::WfpInvalidOperation => "WFP_INVALID_OPERATION",
            ErrorTypeEnum::DriverPnpWatchdog => "DRIVER_PNP_WATCHDOG",
            ErrorTypeEnum::WorkerThreadReturnedWithNonDefaultWorkloadClass => {
                "WORKER_THREAD_RETURNED_WITH_NON_DEFAULT_WORKLOAD_CLASS"
            }
            ErrorTypeEnum::EfsFatalError => "EFS_FATAL_ERROR",
            ErrorTypeEnum::UcmucsiFailure => "UCMUCSI_FAILURE",
            ErrorTypeEnum::HalIommuInternalError => "HAL_IOMMU_INTERNAL_ERROR",
            ErrorTypeEnum::HalBlockedProcessorInternalError => {
                "HAL_BLOCKED_PROCESSOR_INTERNAL_ERROR"
            }
            ErrorTypeEnum::IpiWatchdogTimeout => "IPI_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::DmaCommonBufferVectorError => "DMA_COMMON_BUFFER_VECTOR_ERROR",
            ErrorTypeEnum::BugcodeMbbadapterDriver => "BUGCODE_MBBADAPTER_DRIVER",
            ErrorTypeEnum::BugcodeWifiadapterDriver => "BUGCODE_WIFIADAPTER_DRIVER",
            ErrorTypeEnum::ProcessorStartTimeout => "PROCESSOR_START_TIMEOUT",
            ErrorTypeEnum::VideoDxgkrnlSysmmFatalError => "VIDEO_DXGKRNL_SYSMM_FATAL_ERROR",
            ErrorTypeEnum::IllegalAtsInitialization => "ILLEGAL_ATS_INITIALIZATION",
            ErrorTypeEnum::SecurePciConfigSpaceAccessViolation => {
                "SECURE_PCI_CONFIG_SPACE_ACCESS_VIOLATION"
            }
            ErrorTypeEnum::DamWatchdogTimeout => "DAM_WATCHDOG_TIMEOUT",
            ErrorTypeEnum::HandleErrorOnCriticalThread => "HANDLE_ERROR_ON_CRITICAL_THREAD",
            ErrorTypeEnum::KasanEnlightenmentViolation => "KASAN_ENLIGHTENMENT_VIOLATION",
            ErrorTypeEnum::KasanIllegalAccess => "KASAN_ILLEGAL_ACCESS",
            ErrorTypeEnum::XboxEractrlCsTimeout => "XBOX_ERACTRL_CS_TIMEOUT",
            ErrorTypeEnum::BcBluetoothVerifierFault => "BC_BLUETOOTH_VERIFIER_FAULT",
            ErrorTypeEnum::BcBthminiVerifierFault => "BC_BTHMINI_VERIFIER_FAULT",
            ErrorTypeEnum::HypervisorError => "HYPERVISOR_ERROR",
            ErrorTypeEnum::SystemThreadExceptionNotHandledM => {
                "SYSTEM_THREAD_EXCEPTION_NOT_HANDLED_M"
            }
            ErrorTypeEnum::UnexpectedKernelModeTrapM => "UNEXPECTED_KERNEL_MODE_TRAP_M",
            ErrorTypeEnum::KernelModeExceptionNotHandledM => "KERNEL_MODE_EXCEPTION_NOT_HANDLED_M",
            ErrorTypeEnum::ThreadStuckInDeviceDriverM => "THREAD_STUCK_IN_DEVICE_DRIVER_M",
            ErrorTypeEnum::ThreadTerminateHeldMutex => "THREAD_TERMINATE_HELD_MUTEX",
            ErrorTypeEnum::StatusCannotLoadRegistryFile => "STATUS_CANNOT_LOAD_REGISTRY_FILE",
            ErrorTypeEnum::WinlogonFatalError => "WINLOGON_FATAL_ERROR",
            ErrorTypeEnum::StatusImageChecksumMismatch => "STATUS_IMAGE_CHECKSUM_MISMATCH",
            ErrorTypeEnum::ManuallyInitiatedCrash1 => "MANUALLY_INITIATED_CRASH1",
        }
    }

    pub fn as_code(error_type: ErrorTypeEnum) -> u32 {
        match error_type {
            ErrorTypeEnum::ApcIndexMismatch => 0x1,
            ErrorTypeEnum::DeviceQueueNotBusy => 0x2,
            ErrorTypeEnum::InvalidAffinitySet => 0x3,
            ErrorTypeEnum::InvalidDataAccessTrap => 0x4,
            ErrorTypeEnum::InvalidProcessAttachAttempt => 0x5,
            ErrorTypeEnum::InvalidProcessDetachAttempt => 0x6,
            ErrorTypeEnum::InvalidSoftwareInterrupt => 0x7,
            ErrorTypeEnum::IrqlNotDispatchLevel => 0x8,
            ErrorTypeEnum::IrqlNotGreaterOrEqual => 0x9,
            ErrorTypeEnum::IrqlNotLessOrEqual => 0xa,
            ErrorTypeEnum::NoExceptionHandlingSupport => 0xb,
            ErrorTypeEnum::MaximumWaitObjectsExceeded => 0xc,
            ErrorTypeEnum::MutexLevelNumberViolation => 0xd,
            ErrorTypeEnum::NoUserModeContext => 0xe,
            ErrorTypeEnum::SpinLockAlreadyOwned => 0xf,
            ErrorTypeEnum::SpinLockNotOwned => 0x10,
            ErrorTypeEnum::ThreadNotMutexOwner => 0x11,
            ErrorTypeEnum::TrapCauseUnknown => 0x12,
            ErrorTypeEnum::EmptyThreadReaperList => 0x13,
            ErrorTypeEnum::CreateDeleteLockNotLocked => 0x14,
            ErrorTypeEnum::LastChanceCalledFromKmode => 0x15,
            ErrorTypeEnum::CidHandleCreation => 0x16,
            ErrorTypeEnum::CidHandleDeletion => 0x17,
            ErrorTypeEnum::ReferenceByPointer => 0x18,
            ErrorTypeEnum::BadPoolHeader => 0x19,
            ErrorTypeEnum::MemoryManagement => 0x1a,
            ErrorTypeEnum::PfnShareCount => 0x1b,
            ErrorTypeEnum::PfnReferenceCount => 0x1c,
            ErrorTypeEnum::NoSpinLockAvailable => 0x1d,
            ErrorTypeEnum::KmodeExceptionNotHandled => 0x1e,
            ErrorTypeEnum::SharedResourceConvError => 0x1f,
            ErrorTypeEnum::KernelApcPendingDuringExit => 0x20,
            ErrorTypeEnum::QuotaUnderflow => 0x21,
            ErrorTypeEnum::FileSystem => 0x22,
            ErrorTypeEnum::FatFileSystem => 0x23,
            ErrorTypeEnum::NtfsFileSystem => 0x24,
            ErrorTypeEnum::NpfsFileSystem => 0x25,
            ErrorTypeEnum::CdfsFileSystem => 0x26,
            ErrorTypeEnum::RdrFileSystem => 0x27,
            ErrorTypeEnum::CorruptAccessToken => 0x28,
            ErrorTypeEnum::SecuritySystem => 0x29,
            ErrorTypeEnum::InconsistentIrp => 0x2a,
            ErrorTypeEnum::PanicStackSwitch => 0x2b,
            ErrorTypeEnum::PortDriverInternal => 0x2c,
            ErrorTypeEnum::ScsiDiskDriverInternal => 0x2d,
            ErrorTypeEnum::DataBusError => 0x2e,
            ErrorTypeEnum::InstructionBusError => 0x2f,
            ErrorTypeEnum::SetOfInvalidContext => 0x30,
            ErrorTypeEnum::Phase0InitializationFailed => 0x31,
            ErrorTypeEnum::Phase1InitializationFailed => 0x32,
            ErrorTypeEnum::UnexpectedInitializationCall => 0x33,
            ErrorTypeEnum::CacheManager => 0x34,
            ErrorTypeEnum::NoMoreIrpStackLocations => 0x35,
            ErrorTypeEnum::DeviceReferenceCountNotZero => 0x36,
            ErrorTypeEnum::FloppyInternalError => 0x37,
            ErrorTypeEnum::SerialDriverInternal => 0x38,
            ErrorTypeEnum::SystemExitOwnedMutex => 0x39,
            ErrorTypeEnum::SystemUnwindPreviousUser => 0x3a,
            ErrorTypeEnum::SystemServiceException => 0x3b,
            ErrorTypeEnum::InterruptUnwindAttempted => 0x3c,
            ErrorTypeEnum::InterruptExceptionNotHandled => 0x3d,
            ErrorTypeEnum::MultiprocessorConfigurationNotSupported => 0x3e,
            ErrorTypeEnum::NoMoreSystemPtes => 0x3f,
            ErrorTypeEnum::TargetMdlTooSmall => 0x40,
            ErrorTypeEnum::MustSucceedPoolEmpty => 0x41,
            ErrorTypeEnum::AtdiskDriverInternal => 0x42,
            ErrorTypeEnum::NoSuchPartition => 0x43,
            ErrorTypeEnum::MultipleIrpCompleteRequests => 0x44,
            ErrorTypeEnum::InsufficientSystemMapRegs => 0x45,
            ErrorTypeEnum::DerefUnknownLogonSession => 0x46,
            ErrorTypeEnum::RefUnknownLogonSession => 0x47,
            ErrorTypeEnum::CancelStateInCompletedIrp => 0x48,
            ErrorTypeEnum::PageFaultWithInterruptsOff => 0x49,
            ErrorTypeEnum::IrqlGtZeroAtSystemService => 0x4a,
            ErrorTypeEnum::StreamsInternalError => 0x4b,
            ErrorTypeEnum::FatalUnhandledHardError => 0x4c,
            ErrorTypeEnum::NoPagesAvailable => 0x4d,
            ErrorTypeEnum::PfnListCorrupt => 0x4e,
            ErrorTypeEnum::NdisInternalError => 0x4f,
            ErrorTypeEnum::PageFaultInNonpagedArea => 0x50,
            ErrorTypeEnum::RegistryError => 0x51,
            ErrorTypeEnum::MailslotFileSystem => 0x52,
            ErrorTypeEnum::NoBootDevice => 0x53,
            ErrorTypeEnum::LmServerInternalError => 0x54,
            ErrorTypeEnum::DataCoherencyException => 0x55,
            ErrorTypeEnum::InstructionCoherencyException => 0x56,
            ErrorTypeEnum::XnsInternalError => 0x57,
            ErrorTypeEnum::FtdiskInternalError => 0x58,
            ErrorTypeEnum::PinballFileSystem => 0x59,
            ErrorTypeEnum::CriticalServiceFailed => 0x5a,
            ErrorTypeEnum::SetEnvVarFailed => 0x5b,
            ErrorTypeEnum::HalInitializationFailed => 0x5c,
            ErrorTypeEnum::UnsupportedProcessor => 0x5d,
            ErrorTypeEnum::ObjectInitializationFailed => 0x5e,
            ErrorTypeEnum::SecurityInitializationFailed => 0x5f,
            ErrorTypeEnum::ProcessInitializationFailed => 0x60,
            ErrorTypeEnum::Hal1InitializationFailed => 0x61,
            ErrorTypeEnum::Object1InitializationFailed => 0x62,
            ErrorTypeEnum::Security1InitializationFailed => 0x63,
            ErrorTypeEnum::SymbolicInitializationFailed => 0x64,
            ErrorTypeEnum::Memory1InitializationFailed => 0x65,
            ErrorTypeEnum::CacheInitializationFailed => 0x66,
            ErrorTypeEnum::ConfigInitializationFailed => 0x67,
            ErrorTypeEnum::FileInitializationFailed => 0x68,
            ErrorTypeEnum::Io1InitializationFailed => 0x69,
            ErrorTypeEnum::LpcInitializationFailed => 0x6a,
            ErrorTypeEnum::Process1InitializationFailed => 0x6b,
            ErrorTypeEnum::RefmonInitializationFailed => 0x6c,
            ErrorTypeEnum::Session1InitializationFailed => 0x6d,
            ErrorTypeEnum::Session2InitializationFailed => 0x6e,
            ErrorTypeEnum::Session3InitializationFailed => 0x6f,
            ErrorTypeEnum::Session4InitializationFailed => 0x70,
            ErrorTypeEnum::Session5InitializationFailed => 0x71,
            ErrorTypeEnum::AssignDriveLettersFailed => 0x72,
            ErrorTypeEnum::ConfigListFailed => 0x73,
            ErrorTypeEnum::BadSystemConfigInfo => 0x74,
            ErrorTypeEnum::CannotWriteConfiguration => 0x75,
            ErrorTypeEnum::ProcessHasLockedPages => 0x76,
            ErrorTypeEnum::KernelStackInpageError => 0x77,
            ErrorTypeEnum::Phase0Exception => 0x78,
            ErrorTypeEnum::MismatchedHal => 0x79,
            ErrorTypeEnum::KernelDataInpageError => 0x7a,
            ErrorTypeEnum::InaccessibleBootDevice => 0x7b,
            ErrorTypeEnum::BugcodeNdisDriver => 0x7c,
            ErrorTypeEnum::InstallMoreMemory => 0x7d,
            ErrorTypeEnum::SystemThreadExceptionNotHandled => 0x7e,
            ErrorTypeEnum::UnexpectedKernelModeTrap => 0x7f,
            ErrorTypeEnum::NmiHardwareFailure => 0x80,
            ErrorTypeEnum::SpinLockInitFailure => 0x81,
            ErrorTypeEnum::DfsFileSystem => 0x82,
            ErrorTypeEnum::SetupFailure => 0x85,
            ErrorTypeEnum::MbrChecksumMismatch => 0x8b,
            ErrorTypeEnum::KernelModeExceptionNotHandled => 0x8e,
            ErrorTypeEnum::Pp0InitializationFailed => 0x8f,
            ErrorTypeEnum::Pp1InitializationFailed => 0x90,
            ErrorTypeEnum::UpDriverOnMpSystem => 0x92,
            ErrorTypeEnum::InvalidKernelHandle => 0x93,
            ErrorTypeEnum::KernelStackLockedAtExit => 0x94,
            ErrorTypeEnum::InvalidWorkQueueItem => 0x96,
            ErrorTypeEnum::BoundImageUnsupported => 0x97,
            ErrorTypeEnum::EndOfNtEvaluationPeriod => 0x98,
            ErrorTypeEnum::InvalidRegionOrSegment => 0x99,
            ErrorTypeEnum::SystemLicenseViolation => 0x9a,
            ErrorTypeEnum::UdfsFileSystem => 0x9b,
            ErrorTypeEnum::MachineCheckException => 0x9c,
            ErrorTypeEnum::UserModeHealthMonitor => 0x9e,
            ErrorTypeEnum::DriverPowerStateFailure => 0x9f,
            ErrorTypeEnum::InternalPowerError => 0xa0,
            ErrorTypeEnum::PciBusDriverInternal => 0xa1,
            ErrorTypeEnum::MemoryImageCorrupt => 0xa2,
            ErrorTypeEnum::AcpiDriverInternal => 0xa3,
            ErrorTypeEnum::CnssFileSystemFilter => 0xa4,
            ErrorTypeEnum::AcpiBiosError => 0xa5,
            ErrorTypeEnum::BadExhandle => 0xa7,
            ErrorTypeEnum::HalMemoryAllocation => 0xac,
            ErrorTypeEnum::VideoDriverDebugReportRequest => 0xad,
            ErrorTypeEnum::BgiDetectedViolation => 0xb1,
            ErrorTypeEnum::VideoDriverInitFailure => 0xb4,
            ErrorTypeEnum::AttemptedSwitchFromDpc => 0xb8,
            ErrorTypeEnum::ChipsetDetectedError => 0xb9,
            ErrorTypeEnum::SessionHasValidViewsOnExit => 0xba,
            ErrorTypeEnum::NetworkBootInitializationFailed => 0xbb,
            ErrorTypeEnum::NetworkBootDuplicateAddress => 0xbc,
            ErrorTypeEnum::InvalidHibernatedState => 0xbd,
            ErrorTypeEnum::AttemptedWriteToReadonlyMemory => 0xbe,
            ErrorTypeEnum::MutexAlreadyOwned => 0xbf,
            ErrorTypeEnum::SpecialPoolDetectedMemoryCorruption => 0xc1,
            ErrorTypeEnum::BadPoolCaller => 0xc2,
            ErrorTypeEnum::DriverVerifierDetectedViolation => 0xc4,
            ErrorTypeEnum::DriverCorruptedExpool => 0xc5,
            ErrorTypeEnum::DriverCaughtModifyingFreedPool => 0xc6,
            ErrorTypeEnum::TimerOrDpcInvalid => 0xc7,
            ErrorTypeEnum::IrqlUnexpectedValue => 0xc8,
            ErrorTypeEnum::DriverVerifierIomanagerViolation => 0xc9,
            ErrorTypeEnum::PnpDetectedFatalError => 0xca,
            ErrorTypeEnum::DriverLeftLockedPagesInProcess => 0xcb,
            ErrorTypeEnum::PageFaultInFreedSpecialPool => 0xcc,
            ErrorTypeEnum::PageFaultBeyondEndOfAllocation => 0xcd,
            ErrorTypeEnum::DriverUnloadedWithoutCancellingPendingOperations => 0xce,
            ErrorTypeEnum::TerminalServerDriverMadeIncorrectMemoryReference => 0xcf,
            ErrorTypeEnum::DriverCorruptedMmpool => 0xd0,
            ErrorTypeEnum::DriverIrqlNotLessOrEqual => 0xd1,
            ErrorTypeEnum::BugcodeIdDriver => 0xd2,
            ErrorTypeEnum::DriverPortionMustBeNonpaged => 0xd3,
            ErrorTypeEnum::SystemScanAtRaisedIrqlCaughtImproperDriverUnload => 0xd4,
            ErrorTypeEnum::DriverPageFaultInFreedSpecialPool => 0xd5,
            ErrorTypeEnum::DriverPageFaultBeyondEndOfAllocation => 0xd6,
            ErrorTypeEnum::DriverUnmappingInvalidView => 0xd7,
            ErrorTypeEnum::DriverUsedExcessivePtes => 0xd8,
            ErrorTypeEnum::LockedPagesTrackerCorruption => 0xd9,
            ErrorTypeEnum::SystemPteMisuse => 0xda,
            ErrorTypeEnum::DriverCorruptedSysptes => 0xdb,
            ErrorTypeEnum::DriverInvalidStackAccess => 0xdc,
            ErrorTypeEnum::PoolCorruptionInFileArea => 0xde,
            ErrorTypeEnum::ImpersonatingWorkerThread => 0xdf,
            ErrorTypeEnum::AcpiBiosFatalError => 0xe0,
            ErrorTypeEnum::WorkerThreadReturnedAtBadIrql => 0xe1,
            ErrorTypeEnum::ManuallyInitiatedCrash => 0xe2,
            ErrorTypeEnum::ResourceNotOwned => 0xe3,
            ErrorTypeEnum::WorkerInvalid => 0xe4,
            ErrorTypeEnum::DriverVerifierDmaViolation => 0xe6,
            ErrorTypeEnum::InvalidFloatingPointState => 0xe7,
            ErrorTypeEnum::InvalidCancelOfFileOpen => 0xe8,
            ErrorTypeEnum::ActiveExWorkerThreadTermination => 0xe9,
            ErrorTypeEnum::ThreadStuckInDeviceDriver => 0xea,
            ErrorTypeEnum::DirtyMappedPagesCongestion => 0xeb,
            ErrorTypeEnum::SessionHasValidSpecialPoolOnExit => 0xec,
            ErrorTypeEnum::UnmountableBootVolume => 0xed,
            ErrorTypeEnum::CriticalProcessDied => 0xef,
            ErrorTypeEnum::StorageMiniportError => 0xf0,
            ErrorTypeEnum::ScsiVerifierDetectedViolation => 0xf1,
            ErrorTypeEnum::HardwareInterruptStorm => 0xf2,
            ErrorTypeEnum::DisorderlyShutdown => 0xf3,
            ErrorTypeEnum::CriticalObjectTermination => 0xf4,
            ErrorTypeEnum::FltmgrFileSystem => 0xf5,
            ErrorTypeEnum::PciVerifierDetectedViolation => 0xf6,
            ErrorTypeEnum::DriverOverranStackBuffer => 0xf7,
            ErrorTypeEnum::RamdiskBootInitializationFailed => 0xf8,
            ErrorTypeEnum::DriverReturnedStatusReparseForVolumeOpen => 0xf9,
            ErrorTypeEnum::HttpDriverCorrupted => 0xfa,
            ErrorTypeEnum::AttemptedExecuteOfNoexecuteMemory => 0xfc,
            ErrorTypeEnum::DirtyNowritePagesCongestion => 0xfd,
            ErrorTypeEnum::BugcodeUsbDriver => 0xfe,
            ErrorTypeEnum::ReserveQueueOverflow => 0xff,
            ErrorTypeEnum::LoaderBlockMismatch => 0x100,
            ErrorTypeEnum::ClockWatchdogTimeout => 0x101,
            ErrorTypeEnum::DpcWatchdogTimeout => 0x102,
            ErrorTypeEnum::MupFileSystem => 0x103,
            ErrorTypeEnum::AgpInvalidAccess => 0x104,
            ErrorTypeEnum::AgpGartCorruption => 0x105,
            ErrorTypeEnum::AgpIllegallyReprogrammed => 0x106,
            ErrorTypeEnum::ThirdPartyFileSystemFailure => 0x108,
            ErrorTypeEnum::CriticalStructureCorruption => 0x109,
            ErrorTypeEnum::AppTaggingInitializationFailed => 0x10a,
            ErrorTypeEnum::FsrtlExtraCreateParameterViolation => 0x10c,
            ErrorTypeEnum::WdfViolation => 0x10d,
            ErrorTypeEnum::VideoMemoryManagementInternal => 0x10e,
            ErrorTypeEnum::ResourceManagerExceptionNotHandled => 0x10f,
            ErrorTypeEnum::RecursiveNmi => 0x111,
            ErrorTypeEnum::MsrpcStateViolation => 0x112,
            ErrorTypeEnum::VideoDxgkrnlFatalError => 0x113,
            ErrorTypeEnum::VideoShadowDriverFatalError => 0x114,
            ErrorTypeEnum::AgpInternal => 0x115,
            ErrorTypeEnum::VideoTdrFailure => 0x116,
            ErrorTypeEnum::VideoTdrTimeoutDetected => 0x117,
            ErrorTypeEnum::VideoSchedulerInternalError => 0x119,
            ErrorTypeEnum::EmInitializationFailure => 0x11a,
            ErrorTypeEnum::DriverReturnedHoldingCancelLock => 0x11b,
            ErrorTypeEnum::AttemptedWriteToCmProtectedStorage => 0x11c,
            ErrorTypeEnum::EventTracingFatalError => 0x11d,
            ErrorTypeEnum::TooManyRecursiveFaults => 0x11e,
            ErrorTypeEnum::InvalidDriverHandle => 0x11f,
            ErrorTypeEnum::BitlockerFatalError => 0x120,
            ErrorTypeEnum::DriverViolation => 0x121,
            ErrorTypeEnum::WheaInternalError => 0x122,
            ErrorTypeEnum::CryptoSelfTestFailure => 0x123,
            ErrorTypeEnum::WheaUncorrectableError => 0x124,
            ErrorTypeEnum::NmrInvalidState => 0x125,
            ErrorTypeEnum::NetioInvalidPoolCaller => 0x126,
            ErrorTypeEnum::PageNotZero => 0x127,
            ErrorTypeEnum::WorkerThreadReturnedWithBadIoPriority => 0x128,
            ErrorTypeEnum::WorkerThreadReturnedWithBadPagingIoPriority => 0x129,
            ErrorTypeEnum::MuiNoValidSystemLanguage => 0x12a,
            ErrorTypeEnum::FaultyHardwareCorruptedPage => 0x12b,
            ErrorTypeEnum::ExfatFileSystem => 0x12c,
            ErrorTypeEnum::VolsnapOverlappedTableAccess => 0x12d,
            ErrorTypeEnum::InvalidMdlRange => 0x12e,
            ErrorTypeEnum::VhdBootInitializationFailed => 0x12f,
            ErrorTypeEnum::DynamicAddProcessorMismatch => 0x130,
            ErrorTypeEnum::InvalidExtendedProcessorState => 0x131,
            ErrorTypeEnum::ResourceOwnerPointerInvalid => 0x132,
            ErrorTypeEnum::DpcWatchdogViolation => 0x133,
            ErrorTypeEnum::DriveExtender => 0x134,
            ErrorTypeEnum::RegistryFilterDriverException => 0x135,
            ErrorTypeEnum::VhdBootHostVolumeNotEnoughSpace => 0x136,
            ErrorTypeEnum::Win32kHandleManager => 0x137,
            ErrorTypeEnum::GpioControllerDriverError => 0x138,
            ErrorTypeEnum::KernelSecurityCheckFailure => 0x139,
            ErrorTypeEnum::KernelModeHeapCorruption => 0x13a,
            ErrorTypeEnum::PassiveInterruptError => 0x13b,
            ErrorTypeEnum::InvalidIoBoostState => 0x13c,
            ErrorTypeEnum::CriticalInitializationFailure => 0x13d,
            ErrorTypeEnum::StorageDeviceAbnormalityDetected => 0x140,
            ErrorTypeEnum::ProcessorDriverInternal => 0x143,
            ErrorTypeEnum::BugcodeUsb3Driver => 0x144,
            ErrorTypeEnum::SecureBootViolation => 0x145,
            ErrorTypeEnum::AbnormalResetDetected => 0x147,
            ErrorTypeEnum::RefsFileSystem => 0x149,
            ErrorTypeEnum::KernelWmiInternal => 0x14a,
            ErrorTypeEnum::SocSubsystemFailure => 0x14b,
            ErrorTypeEnum::FatalAbnormalResetError => 0x14c,
            ErrorTypeEnum::ExceptionScopeInvalid => 0x14d,
            ErrorTypeEnum::SocCriticalDeviceRemoved => 0x14e,
            ErrorTypeEnum::PdcWatchdogTimeout => 0x14f,
            ErrorTypeEnum::TcpipAoacNicActiveReferenceLeak => 0x150,
            ErrorTypeEnum::UnsupportedInstructionMode => 0x151,
            ErrorTypeEnum::InvalidPushLockFlags => 0x152,
            ErrorTypeEnum::KernelLockEntryLeakedOnThreadTermination => 0x153,
            ErrorTypeEnum::UnexpectedStoreException => 0x154,
            ErrorTypeEnum::OsDataTampering => 0x155,
            ErrorTypeEnum::KernelThreadPriorityFloorViolation => 0x157,
            ErrorTypeEnum::IllegalIommuPageFault => 0x158,
            ErrorTypeEnum::HalIllegalIommuPageFault => 0x159,
            ErrorTypeEnum::SdbusInternalError => 0x15a,
            ErrorTypeEnum::WorkerThreadReturnedWithSystemPagePriorityActive => 0x15b,
            ErrorTypeEnum::Win32kAtomicCheckFailure => 0x160,
            ErrorTypeEnum::KernelAutoBoostInvalidLockRelease => 0x162,
            ErrorTypeEnum::WorkerThreadTestCondition => 0x163,
            ErrorTypeEnum::Win32kCriticalFailure => 0x164,
            ErrorTypeEnum::InvalidRundownProtectionFlags => 0x16c,
            ErrorTypeEnum::InvalidSlotAllocatorFlags => 0x16d,
            ErrorTypeEnum::EresourceInvalidRelease => 0x16e,
            ErrorTypeEnum::ClusterCsvClussvcDisconnectWatchdog => 0x170,
            ErrorTypeEnum::CryptoLibraryInternalError => 0x171,
            ErrorTypeEnum::CoremsgcallInternalError => 0x173,
            ErrorTypeEnum::CoremsgInternalError => 0x174,
            ErrorTypeEnum::ElamDriverDetectedFatalError => 0x178,
            ErrorTypeEnum::ProfilerConfigurationIllegal => 0x17b,
            ErrorTypeEnum::MicrocodeRevisionMismatch => 0x17e,
            ErrorTypeEnum::VideoDwminitTimeoutFallbackBdd => 0x187,
            ErrorTypeEnum::BadObjectHeader => 0x189,
            ErrorTypeEnum::SecureKernelError => 0x18b,
            ErrorTypeEnum::HyperguardViolation => 0x18c,
            ErrorTypeEnum::SecureFaultUnhandled => 0x18d,
            ErrorTypeEnum::KernelPartitionReferenceViolation => 0x18e,
            ErrorTypeEnum::PfDetectedCorruption => 0x191,
            ErrorTypeEnum::KernelAutoBoostLockAcquisitionWithRaisedIrql => 0x192,
            ErrorTypeEnum::LoaderRollbackDetected => 0x196,
            ErrorTypeEnum::Win32kSecurityFailure => 0x197,
            ErrorTypeEnum::KernelStorageSlotInUse => 0x199,
            ErrorTypeEnum::WorkerThreadReturnedWhileAttachedToSilo => 0x19a,
            ErrorTypeEnum::TtmFatalError => 0x19b,
            ErrorTypeEnum::Win32kPowerWatchdogTimeout => 0x19c,
            ErrorTypeEnum::TtmWatchdogTimeout => 0x1a0,
            ErrorTypeEnum::Win32kCalloutWatchdogBugcheck => 0x1a2,
            ErrorTypeEnum::ExceptionOnInvalidStack => 0x1aa,
            ErrorTypeEnum::UnwindOnInvalidStack => 0x1ab,
            ErrorTypeEnum::FastEresourcePreconditionViolation => 0x1c6,
            ErrorTypeEnum::StoreDataStructureCorruption => 0x1c7,
            ErrorTypeEnum::ManuallyInitiatedPowerButtonHold => 0x1c8,
            ErrorTypeEnum::SyntheticWatchdogTimeout => 0x1ca,
            ErrorTypeEnum::InvalidSiloDetach => 0x1cb,
            ErrorTypeEnum::InvalidCallbackStackAddress => 0x1cd,
            ErrorTypeEnum::InvalidKernelStackAddress => 0x1ce,
            ErrorTypeEnum::HardwareWatchdogTimeout => 0x1cf,
            ErrorTypeEnum::CpiFirmwareWatchdogTimeout => 0x1d0,
            ErrorTypeEnum::WorkerThreadInvalidState => 0x1d2,
            ErrorTypeEnum::WfpInvalidOperation => 0x1d3,
            ErrorTypeEnum::DriverPnpWatchdog => 0x1d5,
            ErrorTypeEnum::WorkerThreadReturnedWithNonDefaultWorkloadClass => 0x1d6,
            ErrorTypeEnum::EfsFatalError => 0x1d7,
            ErrorTypeEnum::UcmucsiFailure => 0x1d8,
            ErrorTypeEnum::HalIommuInternalError => 0x1d9,
            ErrorTypeEnum::HalBlockedProcessorInternalError => 0x1da,
            ErrorTypeEnum::IpiWatchdogTimeout => 0x1db,
            ErrorTypeEnum::DmaCommonBufferVectorError => 0x1dc,
            ErrorTypeEnum::BugcodeMbbadapterDriver => 0x1dd,
            ErrorTypeEnum::BugcodeWifiadapterDriver => 0x1de,
            ErrorTypeEnum::ProcessorStartTimeout => 0x1df,
            ErrorTypeEnum::VideoDxgkrnlSysmmFatalError => 0x1e4,
            ErrorTypeEnum::IllegalAtsInitialization => 0x1e9,
            ErrorTypeEnum::SecurePciConfigSpaceAccessViolation => 0x1ea,
            ErrorTypeEnum::DamWatchdogTimeout => 0x1eb,
            ErrorTypeEnum::HandleErrorOnCriticalThread => 0x1ed,
            ErrorTypeEnum::KasanEnlightenmentViolation => 0x1f1,
            ErrorTypeEnum::KasanIllegalAccess => 0x1f2,
            ErrorTypeEnum::XboxEractrlCsTimeout => 0x356,
            ErrorTypeEnum::BcBluetoothVerifierFault => 0xbfe,
            ErrorTypeEnum::BcBthminiVerifierFault => 0xbff,
            ErrorTypeEnum::HypervisorError => 0x20001,
            ErrorTypeEnum::SystemThreadExceptionNotHandledM => 0x1000007e,
            ErrorTypeEnum::UnexpectedKernelModeTrapM => 0x1000007f,
            ErrorTypeEnum::KernelModeExceptionNotHandledM => 0x1000008e,
            ErrorTypeEnum::ThreadStuckInDeviceDriverM => 0x100000ea,
            ErrorTypeEnum::ThreadTerminateHeldMutex => 0x4000008a,
            ErrorTypeEnum::StatusCannotLoadRegistryFile => 0xc0000218,
            ErrorTypeEnum::WinlogonFatalError => 0xc000021a,
            ErrorTypeEnum::StatusImageChecksumMismatch => 0xc0000221,
            ErrorTypeEnum::ManuallyInitiatedCrash1 => 0xdeaddead,
        }
    }
}
